################################################################################
# Clock constraints
################################################################################
create_clock -period 1.600 -name adr_p [get_ports {adr_p[0]}]
create_clock -period 1.600 -name bdr_p_0 [get_ports {bdr_p[0]}]
create_clock -period 1.600 -name cdr_p_0 [get_ports {cdr_p[0]}]
create_clock -period 1.600 -name ddr_p_0 [get_ports {ddr_p[0]}]

create_clock -period 2.000 -name clk_to_fpga_p_0 [get_ports clk_to_fpga_p[0]]
create_clock -period 100.000 -name ext_trigger_p_0 [get_ports ext_trigger_p[0]]

set_clock_groups -name adr_phy_clocks_0 -asynchronous -group [get_clocks -include_generated_clocks adr_p]
set_clock_groups -name bdr_phy_clocks_0 -asynchronous -group [get_clocks -include_generated_clocks bdr_p_0]
set_clock_groups -name cdr_phy_clocks_0 -asynchronous -group [get_clocks -include_generated_clocks cdr_p_0]
set_clock_groups -name ddr_phy_clocks_0 -asynchronous -group [get_clocks -include_generated_clocks ddr_p_0]
set_clock_groups -name clk_to_fpga_phy_clocks_0 -asynchronous -group [get_clocks -include_generated_clocks clk_to_fpga_p_0]

# VIRTUAL CLOCKS -> CLOCK WIZZARD
create_clock -period 8.000 -name VIRTUAL_axi_fmc126_clk125 -waveform {0.000 4.000}


################################################################################
# Input delay constraints
################################################################################

#Channel A
#set_input_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 2.000 [get_ports {ad_p[0][*]}]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 0.200 [get_ports {ad_p[0][*]}]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 2.000 [get_ports {ad_n[0][*]}]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 0.200 [get_ports {ad_n[0][*]}]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 2.000 [get_ports aor_p[0]]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 0.200 [get_ports aor_n[0]]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 2.000 [get_ports aor_p[0]]
#set_input_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 0.200 [get_ports aor_n[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {ad_p[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {ad_p[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {ad_n[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {ad_n[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports aor_p[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports aor_n[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports aor_p[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports aor_n[0]]

#Channel B
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {bd_p[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {bd_n[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {bd_p[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {bd_n[0][*]}]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports bor_p[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports bor_n[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports bor_p[0]]
set_input_delay -clock [get_clocks bdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports bor_n[0]]

#Channel C
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {cd_p[0][*]}]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {cd_n[0][*]}]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {cd_p[0][*]}]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {cd_n[0][*]}]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports cor_p[0]]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports cor_n[0]]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -min -add_delay 2.000 [get_ports cor_p[0]]
set_input_delay -clock [get_clocks cdr_p_0] -clock_fall -max -add_delay 0.200 [get_ports cor_n[0]]

#Channel D
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {dd_p[0][*]}]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {dd_n[0][*]}]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -min -add_delay 2.000 [get_ports {dd_p[0][*]}]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -max -add_delay 0.200 [get_ports {dd_n[0][*]}]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -min -add_delay 2.000 [get_ports dor_p[0]]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -max -add_delay 0.200 [get_ports dor_n[0]]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -min -add_delay 2.000 [get_ports dor_p[0]]
set_input_delay -clock [get_clocks ddr_p_0] -clock_fall -max -add_delay 0.200 [get_ports dor_n[0]]

#Misc
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -min -add_delay 3.000 [get_ports prsnt_m2c_l[0]]
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -max -add_delay 4.500 [get_ports prsnt_m2c_l[0]]
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -min -add_delay 3.000 [get_ports pg_m2c[0]]
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -max -add_delay 4.500 [get_ports pg_m2c[0]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -min -add_delay 3.000 [get_ports ext_trigger_p[0]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -max -add_delay 4.500 [get_ports ext_trigger_p[0]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -min -add_delay 3.000 [get_ports ext_trigger_n[0]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -max -add_delay 4.500 [get_ports ext_trigger_n[0]]
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -min -add_delay 3.000 [get_ports fmc_to_cpld[0]]
set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -max -add_delay 4.500 [get_ports fmc_to_cpld[0]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -min -add_delay 3.000 [get_ports front_io_fmc[0][*]]
#set_input_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -max -add_delay 4.500 [get_ports front_io_fmc[0][*]]

################################################################################
# Output delay constraints
################################################################################

#Misc
set_output_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -min -add_delay 3.000 [get_ports {fmc_to_cpld[0][*]}]
set_output_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -max -add_delay 4.500 [get_ports {fmc_to_cpld[0][*]}]
#set_output_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -min -add_delay 3.000 [get_ports front_io_fmc[0][*]]
#set_output_delay -clock [get_clocks VIRTUAL_axi_fmc126_clk125] -clock_fall -max -add_delay 4.500 [get_ports front_io_fmc[0][*]]
set_output_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 3.000 [get_ports sync_from_fpga_n[0]]
set_output_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 4.500 [get_ports sync_from_fpga_n[0]]
set_output_delay -clock [get_clocks adr_p] -clock_fall -min -add_delay 3.000 [get_ports sync_from_fpga_p[0]]
set_output_delay -clock [get_clocks adr_p] -clock_fall -max -add_delay 4.500 [get_ports sync_from_fpga_p[0]]

################################################################################
# FMC signals (FMC126 on PC821 primary side)
################################################################################
set_property PACKAGE_PIN N28 [get_ports clk_to_fpga_p[0]]
set_property PACKAGE_PIN N29 [get_ports clk_to_fpga_n[0]]
set_property PACKAGE_PIN N31 [get_ports ext_trigger_p[0]]
set_property PACKAGE_PIN M31 [get_ports ext_trigger_n[0]]
set_property PACKAGE_PIN AC31 [get_ports sync_from_fpga_p[0]]
set_property PACKAGE_PIN AD31 [get_ports sync_from_fpga_n[0]]

set_property PACKAGE_PIN M30 [get_ports adr_p[0]]
set_property PACKAGE_PIN L30 [get_ports adr_n[0]]
set_property PACKAGE_PIN N32 [get_ports {ad_p[0][0]}]
set_property PACKAGE_PIN M32 [get_ports {ad_n[0][0]}]
set_property PACKAGE_PIN M29 [get_ports {ad_p[0][1]}]
set_property PACKAGE_PIN L29 [get_ports {ad_n[0][1]}]
set_property PACKAGE_PIN R30 [get_ports {ad_p[0][2]}]
set_property PACKAGE_PIN P30 [get_ports {ad_n[0][2]}]
set_property PACKAGE_PIN K30 [get_ports {ad_p[0][3]}]
set_property PACKAGE_PIN K31 [get_ports {ad_n[0][3]}]
set_property PACKAGE_PIN L28 [get_ports {ad_p[0][4]}]
set_property PACKAGE_PIN K28 [get_ports {ad_n[0][4]}]
set_property PACKAGE_PIN U29 [get_ports {ad_p[0][5]}]
set_property PACKAGE_PIN T29 [get_ports {ad_n[0][5]}]
set_property PACKAGE_PIN U30 [get_ports {ad_p[0][6]}]
set_property PACKAGE_PIN T30 [get_ports {ad_n[0][6]}]
set_property PACKAGE_PIN N26 [get_ports {ad_p[0][7]}]
set_property PACKAGE_PIN N27 [get_ports {ad_n[0][7]}]
set_property PACKAGE_PIN W28 [get_ports {ad_p[0][8]}]
set_property PACKAGE_PIN Y28 [get_ports {ad_n[0][8]}]
set_property PACKAGE_PIN V28 [get_ports {ad_p[0][9]}]
set_property PACKAGE_PIN V29 [get_ports {ad_n[0][9]}]
set_property PACKAGE_PIN AJ18 [get_ports aor_p[0]]
set_property PACKAGE_PIN AJ19 [get_ports aor_n[0]]

set_property PACKAGE_PIN AC32 [get_ports bdr_p[0]]
set_property PACKAGE_PIN AC33 [get_ports bdr_n[0]]
set_property PACKAGE_PIN AB31 [get_ports {bd_p[0][0]}]
set_property PACKAGE_PIN AB32 [get_ports {bd_n[0][0]}]
set_property PACKAGE_PIN AD28 [get_ports {bd_p[0][1]}]
set_property PACKAGE_PIN AE28 [get_ports {bd_n[0][1]}]
set_property PACKAGE_PIN Y27  [get_ports {bd_p[0][2]}]
set_property PACKAGE_PIN AA27 [get_ports {bd_n[0][2]}]
set_property PACKAGE_PIN AF32 [get_ports {bd_p[0][3]}]
set_property PACKAGE_PIN AG32 [get_ports {bd_n[0][3]}]
set_property PACKAGE_PIN AE33 [get_ports {bd_p[0][4]}]
set_property PACKAGE_PIN AF33 [get_ports {bd_n[0][4]}]
set_property PACKAGE_PIN AF27 [get_ports {bd_p[0][5]}]
set_property PACKAGE_PIN AF28 [get_ports {bd_n[0][5]}]
set_property PACKAGE_PIN AD29 [get_ports {bd_p[0][6]}]
set_property PACKAGE_PIN AD30 [get_ports {bd_n[0][6]}]
set_property PACKAGE_PIN AE30 [get_ports {bd_p[0][7]}]
set_property PACKAGE_PIN AE31 [get_ports {bd_n[0][7]}]
set_property PACKAGE_PIN AF29 [get_ports {bd_p[0][8]}]
set_property PACKAGE_PIN AF30 [get_ports {bd_n[0][8]}]
set_property PACKAGE_PIN AD33 [get_ports {bd_p[0][9]}]
set_property PACKAGE_PIN AD34 [get_ports {bd_n[0][9]}]
set_property PACKAGE_PIN AM19 [get_ports bor_p[0]]
set_property PACKAGE_PIN AN19 [get_ports bor_n[0]]

set_property PACKAGE_PIN AL23 [get_ports cdr_p[0]]
set_property PACKAGE_PIN AL24 [get_ports cdr_n[0]]
set_property PACKAGE_PIN AJ23 [get_ports {cd_p[0][0]}]
set_property PACKAGE_PIN AK23 [get_ports {cd_n[0][0]}]
set_property PACKAGE_PIN AP25 [get_ports {cd_p[0][1]}]
set_property PACKAGE_PIN AP26 [get_ports {cd_n[0][1]}]
set_property PACKAGE_PIN AL25 [get_ports {cd_p[0][2]}]
set_property PACKAGE_PIN AM25 [get_ports {cd_n[0][2]}]
set_property PACKAGE_PIN AK26 [get_ports {cd_p[0][3]}]
set_property PACKAGE_PIN AK27 [get_ports {cd_n[0][3]}]
set_property PACKAGE_PIN AM26 [get_ports {cd_p[0][4]}]
set_property PACKAGE_PIN AN26 [get_ports {cd_n[0][4]}]
set_property PACKAGE_PIN AG27 [get_ports {cd_p[0][5]}]
set_property PACKAGE_PIN AH27 [get_ports {cd_n[0][5]}]
set_property PACKAGE_PIN AN24 [get_ports {cd_p[0][6]}]
set_property PACKAGE_PIN AP24 [get_ports {cd_n[0][6]}]
set_property PACKAGE_PIN AG25 [get_ports {cd_p[0][7]}]
set_property PACKAGE_PIN AG26 [get_ports {cd_n[0][7]}]
set_property PACKAGE_PIN AH26 [get_ports {cd_p[0][8]}]
set_property PACKAGE_PIN AJ26 [get_ports {cd_n[0][8]}]
set_property PACKAGE_PIN AM21 [get_ports {cd_p[0][9]}]
set_property PACKAGE_PIN AM22 [get_ports {cd_n[0][9]}]
set_property PACKAGE_PIN AN22 [get_ports cor_p[0]]
set_property PACKAGE_PIN AN23 [get_ports cor_n[0]]

set_property PACKAGE_PIN AL13 [get_ports ddr_p[0]]
set_property PACKAGE_PIN AL12 [get_ports ddr_n[0]]
set_property PACKAGE_PIN AK18 [get_ports {dd_p[0][0]}]
set_property PACKAGE_PIN AL18 [get_ports {dd_n[0][0]}]
set_property PACKAGE_PIN AM16 [get_ports {dd_p[0][1]}]
set_property PACKAGE_PIN AN16 [get_ports {dd_n[0][1]}]
set_property PACKAGE_PIN AL17 [get_ports {dd_p[0][2]}]
set_property PACKAGE_PIN AM17 [get_ports {dd_n[0][2]}]
set_property PACKAGE_PIN AP15 [get_ports {dd_p[0][3]}]
set_property PACKAGE_PIN AP14 [get_ports {dd_n[0][3]}]
set_property PACKAGE_PIN AG12 [get_ports {dd_p[0][4]}]
set_property PACKAGE_PIN AG11 [get_ports {dd_n[0][4]}]
set_property PACKAGE_PIN AM14 [get_ports {dd_p[0][5]}]
set_property PACKAGE_PIN AN13 [get_ports {dd_n[0][5]}]
set_property PACKAGE_PIN AH16 [get_ports {dd_p[0][6]}]
set_property PACKAGE_PIN AJ16 [get_ports {dd_n[0][6]}]
set_property PACKAGE_PIN AH13 [get_ports {dd_p[0][7]}]
set_property PACKAGE_PIN AJ13 [get_ports {dd_n[0][7]}]
set_property PACKAGE_PIN AJ15 [get_ports {dd_p[0][8]}]
set_property PACKAGE_PIN AJ14 [get_ports {dd_n[0][8]}]
set_property PACKAGE_PIN AK11 [get_ports {dd_p[0][9]}]
set_property PACKAGE_PIN AK10 [get_ports {dd_n[0][9]}]
set_property PACKAGE_PIN AL15 [get_ports dor_p[0]]
set_property PACKAGE_PIN AL14 [get_ports dor_n[0]]

set_property PACKAGE_PIN AP21 [get_ports {fmc_to_cpld[0][0]}]
set_property PACKAGE_PIN AR22 [get_ports {fmc_to_cpld[0][1]}]
set_property PACKAGE_PIN AL10 [get_ports {fmc_to_cpld[0][2]}]
set_property PACKAGE_PIN AM10 [get_ports {fmc_to_cpld[0][3]}]

set_property PACKAGE_PIN AR13 [get_ports {front_io_fmc[0][0]}]
set_property PACKAGE_PIN AR12 [get_ports {front_io_fmc[0][1]}]
set_property PACKAGE_PIN AR17 [get_ports {front_io_fmc[0][2]}]
set_property PACKAGE_PIN AR16 [get_ports {front_io_fmc[0][3]}]

set_property PACKAGE_PIN AY16 [get_ports pg_m2c[0]]
set_property PACKAGE_PIN BB16 [get_ports prsnt_m2c_l[0]]

set_property IOSTANDARD LVDS [get_ports {ad_n[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {ad_n[0][*]}]
set_property IOSTANDARD LVDS [get_ports {ad_p[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {ad_p[0][*]}]
set_property IOSTANDARD LVDS [get_ports {bd_n[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {bd_n[0][*]}]
set_property IOSTANDARD LVDS [get_ports {bd_p[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {bd_p[0][*]}]
set_property IOSTANDARD LVDS [get_ports {cd_n[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {cd_n[0][*]}]
set_property IOSTANDARD LVDS [get_ports {cd_p[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {cd_p[0][*]}]
set_property IOSTANDARD LVDS [get_ports {dd_n[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {dd_n[0][*]}]
set_property IOSTANDARD LVDS [get_ports {dd_p[0][*]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {dd_p[0][*]}]

set_property IOSTANDARD LVCMOS18 [get_ports {fmc_to_cpld[0][*]}]
set_property DRIVE 12 [get_ports {fmc_to_cpld[0][*]}]
set_property SLEW SLOW [get_ports {fmc_to_cpld[0][*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {front_io_fmc[0][*]}]
set_property DRIVE 12  [get_ports {front_io_fmc[0][*]}]
set_property SLEW SLOW [get_ports {front_io_fmc[0][*]}]

set_property IOSTANDARD LVDS [get_ports {clk_to_fpga_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {clk_to_fpga_n[0]}]
set_property IOSTANDARD LVDS [get_ports {clk_to_fpga_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {clk_to_fpga_p[0]}]
set_property IOSTANDARD LVDS [get_ports {ext_trigger_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {ext_trigger_n[0]}]
set_property IOSTANDARD LVDS [get_ports {ext_trigger_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {ext_trigger_p[0]}]

set_property IOSTANDARD LVDS [get_ports sync_from_fpga_n[0]]
set_property IOSTANDARD LVDS [get_ports sync_from_fpga_p[0]]


set_property DIFF_TERM_ADV=TERM_100 [get_ports {adr_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {adr_p[0]}]
set_property IOSTANDARD LVDS [get_ports {aor_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {aor_n[0]}]
set_property IOSTANDARD LVDS [get_ports {aor_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {aor_p[0]}]
set_property IOSTANDARD LVDS [get_ports {bor_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {bor_n[0]}]
set_property IOSTANDARD LVDS [get_ports {bor_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {bor_p[0]}]
set_property IOSTANDARD LVDS [get_ports {cor_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {cor_n[0]}]
set_property IOSTANDARD LVDS [get_ports {cor_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {cor_p[0]}]
set_property IOSTANDARD LVDS [get_ports {dor_n[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {dor_n[0]}]
set_property IOSTANDARD LVDS [get_ports {dor_p[0]}]
set_property DIFF_TERM_ADV=TERM_100 [get_ports {dor_p[0]}]

set_property IOSTANDARD LVDS [get_ports adr_n[0]]
set_property IOSTANDARD LVDS [get_ports adr_p[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports bdr_n[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports bdr_p[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports cdr_n[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports cdr_p[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports ddr_n[0]]
#set_property IOSTANDARD LVCMOS18 [get_ports ddr_p[0]]
set_property IOSTANDARD LVDS [get_ports bdr_n[0]]
set_property IOSTANDARD LVDS [get_ports bdr_p[0]]
set_property IOSTANDARD LVDS [get_ports cdr_n[0]]
set_property IOSTANDARD LVDS [get_ports cdr_p[0]]
set_property IOSTANDARD LVDS [get_ports ddr_n[0]]
set_property IOSTANDARD LVDS [get_ports ddr_p[0]]

set_property IOSTANDARD LVCMOS33 [get_ports pg_m2c[0]]
set_property IOSTANDARD LVCMOS33 [get_ports prsnt_m2c_l[0]]

