-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hsd_raw is
generic (
    C_S_AXI_BUS_A_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_BUS_A_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sync : IN STD_LOGIC;
    x0_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x1_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x2_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x3_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x4_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x5_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x6_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x7_V : IN STD_LOGIC_VECTOR (10 downto 0);
    y0_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y1_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y2_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y3_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y4_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y5_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y6_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y7_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    t0_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t0_V_ap_vld : OUT STD_LOGIC;
    t1_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t1_V_ap_vld : OUT STD_LOGIC;
    t2_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t2_V_ap_vld : OUT STD_LOGIC;
    t3_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t3_V_ap_vld : OUT STD_LOGIC;
    t4_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t4_V_ap_vld : OUT STD_LOGIC;
    t5_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t5_V_ap_vld : OUT STD_LOGIC;
    t6_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t6_V_ap_vld : OUT STD_LOGIC;
    t7_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t7_V_ap_vld : OUT STD_LOGIC;
    yv_V : OUT STD_LOGIC_VECTOR (3 downto 0);
    iy_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    iy_V_ap_vld : OUT STD_LOGIC;
    s_axi_BUS_A_AWVALID : IN STD_LOGIC;
    s_axi_BUS_A_AWREADY : OUT STD_LOGIC;
    s_axi_BUS_A_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_WVALID : IN STD_LOGIC;
    s_axi_BUS_A_WREADY : OUT STD_LOGIC;
    s_axi_BUS_A_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH/8-1 downto 0);
    s_axi_BUS_A_ARVALID : IN STD_LOGIC;
    s_axi_BUS_A_ARREADY : OUT STD_LOGIC;
    s_axi_BUS_A_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_RVALID : OUT STD_LOGIC;
    s_axi_BUS_A_RREADY : IN STD_LOGIC;
    s_axi_BUS_A_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_BUS_A_BVALID : OUT STD_LOGIC;
    s_axi_BUS_A_BREADY : IN STD_LOGIC;
    s_axi_BUS_A_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of hsd_raw is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hsd_raw,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku085-flvb1760-2-e,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.620000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=289,HLS_SYN_LUT=858}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv14_2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal config_a : STD_LOGIC_VECTOR (31 downto 0);
    signal config_b : STD_LOGIC_VECTOR (31 downto 0);
    signal count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_Val2_3_reg_401 : STD_LOGIC_VECTOR (1 downto 0);
    signal x7_V_read_reg_1554 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1554 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1554 : STD_LOGIC_VECTOR (10 downto 0);
    signal x6_V_read_reg_1559 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1559 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1559 : STD_LOGIC_VECTOR (10 downto 0);
    signal x5_V_read_reg_1564 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1564 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1564 : STD_LOGIC_VECTOR (10 downto 0);
    signal x4_V_read_reg_1569 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1569 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1569 : STD_LOGIC_VECTOR (10 downto 0);
    signal x3_V_read_reg_1574 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1574 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1574 : STD_LOGIC_VECTOR (10 downto 0);
    signal x2_V_read_reg_1579 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1579 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1579 : STD_LOGIC_VECTOR (10 downto 0);
    signal x1_V_read_reg_1584 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1584 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1584 : STD_LOGIC_VECTOR (10 downto 0);
    signal x0_V_read_reg_1589 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1589 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1589 : STD_LOGIC_VECTOR (10 downto 0);
    signal sync_read_reg_1594 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_sync_read_reg_1594 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_sync_read_reg_1594 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_2_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_2_reg_1599 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1599 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1599 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_3_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_3_reg_1603 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1603 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1603 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_4_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_4_reg_1607 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1607 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1607 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_5_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_5_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_6_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_6_reg_1615 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1615 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_7_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_7_reg_1619 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1619 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_8_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_8_reg_1623 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1623 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_9_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_9_reg_1627 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1631 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_13_reg_1631 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_assign_3_cast_fu_786_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_9_fu_790_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_9_reg_1641 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1647 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1653 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_reg_1658 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_reg_1665 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_reg_1671 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_11_fu_837_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_11_reg_1676 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_35_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_reg_1683 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_12_fu_850_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_12_reg_1690 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_44_fu_857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_reg_1697 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_reg_1704 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_assign_7_cast_fu_869_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal v_assign_7_cast_reg_1710 : STD_LOGIC_VECTOR (3 downto 0);
    signal g_fu_873_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal g_reg_1715 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_54_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_reg_1723 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_reg_1730 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_reg_1736 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter0_p_Val2_1_reg_334 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_flag_1_reg_347 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_flag_1_phi_fu_350_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_new_1_reg_358 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_new_1_phi_fu_361_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_assign_1_cast_fu_754_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_p_Val2_2_reg_369 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Val2_2_phi_fu_372_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_7_fu_759_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_flag_2_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_flag_2_phi_fu_381_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_new_1_cast_fu_768_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_new_2_reg_390 : STD_LOGIC_VECTOR (1 downto 0);
    signal iy_V_new_2_phi_fu_393_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Val2_3_phi_fu_404_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_8_fu_773_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_flag_3_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_iy_V_new_3_reg_424 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_p_Val2_4_reg_435 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_flag_4_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_flag_4_phi_fu_447_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_new_3_cast_fu_807_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_new_4_reg_455 : STD_LOGIC_VECTOR (2 downto 0);
    signal iy_V_new_4_phi_fu_458_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_5_reg_465 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Val2_5_phi_fu_468_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_10_fu_812_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_flag_5_reg_475 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_flag_5_phi_fu_478_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_new_5_reg_487 : STD_LOGIC_VECTOR (2 downto 0);
    signal iy_V_new_5_phi_fu_490_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_6_reg_499 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Val2_6_phi_fu_502_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_7_reg_510 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Val2_7_phi_fu_513_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_flag_6_reg_521 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_new_6_reg_533 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544 : STD_LOGIC_VECTOR (0 downto 0);
    signal iy_V_flag_7_phi_fu_548_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_flag_7_reg_544 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556 : STD_LOGIC_VECTOR (2 downto 0);
    signal iy_V_new_7_phi_fu_559_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_iy_V_new_7_reg_556 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_8_phi_fu_571_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_8_reg_568 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_s_fu_1541_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_578_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_600_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_622_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_644_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_666_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_688_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_32_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_710_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_41_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_732_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_51_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_914_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal storemerge1_v_cast_c_fu_933_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_21_fu_929_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp1_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_v_fu_965_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge4_v_fu_978_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge4_v_cast_fu_986_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_29_fu_951_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp5_fu_1005_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_demorgan_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_1019_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_1010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_cast_cast_fu_1030_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel_fu_1044_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel1_fu_1051_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel92_cast_fu_1059_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_37_fu_1001_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_36_fu_1078_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_1093_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_demorgan_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_demorgan_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_1127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_1133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_1115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_1147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_1139_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel96_cast_cast_fu_1153_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond2_fu_1161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel3_fu_1166_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel4_fu_1180_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel100_cast_fu_1188_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_46_fu_1074_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp12_fu_1222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_demorgan_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_1236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_demorgan_fu_1248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_1212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_1254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp51_demorgan_fu_1266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_1217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_1272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_1278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_1242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_1227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_fu_1292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel5_fu_1284_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel104_cast_cast_fu_1298_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond5_fu_1306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_1327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel6_fu_1319_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel106_cast_cast_fu_1312_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel7_fu_1333_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel110_cast_fu_1341_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_56_fu_1203_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp20_fu_1375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp60_demorgan_fu_1385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_1389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp67_demorgan_fu_1400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_1405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp76_demorgan_fu_1417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_1365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_1423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp87_demorgan_fu_1435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_1370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_1441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_1447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp27_fu_1429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_1411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_1395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp21_fu_1380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_1461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel8_fu_1453_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel9_fu_1467_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond8_fu_1475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond9_fu_1489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel116_cast_cast_fu_1481_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond10_fu_1502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel10_fu_1494_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel11_fu_1508_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel12_fu_1516_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel122_cast_fu_1524_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_63_fu_1356_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_61_fu_1535_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;
    signal ap_condition_41 : BOOLEAN;
    signal ap_condition_304 : BOOLEAN;
    signal ap_condition_340 : BOOLEAN;

    component hsd_raw_BUS_A_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        config_a : OUT STD_LOGIC_VECTOR (31 downto 0);
        config_b : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    hsd_raw_BUS_A_s_axi_U : component hsd_raw_BUS_A_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_BUS_A_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_BUS_A_DATA_WIDTH)
    port map (
        AWVALID => s_axi_BUS_A_AWVALID,
        AWREADY => s_axi_BUS_A_AWREADY,
        AWADDR => s_axi_BUS_A_AWADDR,
        WVALID => s_axi_BUS_A_WVALID,
        WREADY => s_axi_BUS_A_WREADY,
        WDATA => s_axi_BUS_A_WDATA,
        WSTRB => s_axi_BUS_A_WSTRB,
        ARVALID => s_axi_BUS_A_ARVALID,
        ARREADY => s_axi_BUS_A_ARREADY,
        ARADDR => s_axi_BUS_A_ARADDR,
        RVALID => s_axi_BUS_A_RVALID,
        RREADY => s_axi_BUS_A_RREADY,
        RDATA => s_axi_BUS_A_RDATA,
        RRESP => s_axi_BUS_A_RRESP,
        BVALID => s_axi_BUS_A_BVALID,
        BREADY => s_axi_BUS_A_BREADY,
        BRESP => s_axi_BUS_A_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        config_a => config_a,
        config_b => config_b);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_41 = ap_const_boolean_1)) then
                if ((or_cond_2_fu_594_p2 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334 <= ap_const_lv1_1;
                elsif (not((or_cond_2_fu_594_p2 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334 <= ap_phi_precharge_reg_pp0_iter0_p_Val2_1_reg_334;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_304 = ap_const_boolean_1)) then
                if ((or_cond3_5_reg_1611 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412 <= ap_const_lv1_1;
                elsif (not((or_cond3_5_reg_1611 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412 <= iy_V_flag_2_phi_fu_381_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412 <= ap_phi_precharge_reg_pp0_iter1_iy_V_flag_3_reg_412;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_304 = ap_const_boolean_1)) then
                if ((or_cond3_5_reg_1611 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424 <= p_Val2_3_phi_fu_404_p4;
                elsif (not((or_cond3_5_reg_1611 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424 <= iy_V_new_2_phi_fu_393_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424 <= ap_phi_precharge_reg_pp0_iter1_iy_V_new_3_reg_424;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_304 = ap_const_boolean_1)) then
                if ((or_cond3_5_reg_1611 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435 <= g_9_fu_790_p2;
                elsif (not((or_cond3_5_reg_1611 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435 <= v_assign_3_cast_fu_786_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_4_reg_435;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_340 = ap_const_boolean_1)) then
                if ((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521 <= ap_const_lv1_1;
                elsif (not((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521 <= iy_V_flag_5_phi_fu_478_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_6_reg_521;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_340 = ap_const_boolean_1)) then
                if ((ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_7_reg_544;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_340 = ap_const_boolean_1)) then
                if ((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533 <= p_Val2_6_phi_fu_502_p4;
                elsif (not((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533 <= iy_V_new_5_phi_fu_490_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_6_reg_533;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_340 = ap_const_boolean_1)) then
                if ((ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556 <= p_Val2_7_phi_fu_513_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_7_reg_556;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_340 = ap_const_boolean_1)) then
                if ((ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568 <= g_fu_873_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_8_reg_568;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_3_reg_401_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_304 = ap_const_boolean_1)) then
                if ((or_cond2_4_reg_1607 = ap_const_lv1_0)) then 
                    p_Val2_3_reg_401 <= g_8_fu_773_p2;
                elsif (not((or_cond2_4_reg_1607 = ap_const_lv1_0))) then 
                    p_Val2_3_reg_401 <= p_Val2_2_phi_fu_372_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_Val2_3_reg_401 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1603 <= or_cond1_3_reg_1603;
                ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1607 <= or_cond2_4_reg_1607;
                ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1611 <= or_cond3_5_reg_1611;
                ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 <= or_cond4_6_reg_1615;
                ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 <= or_cond5_7_reg_1619;
                ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 <= or_cond6_8_reg_1623;
                ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 <= or_cond7_9_reg_1627;
                ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1599 <= or_cond_2_reg_1599;
                ap_pipeline_reg_pp0_iter1_sync_read_reg_1594 <= sync_read_reg_1594;
                ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1589 <= x0_V_read_reg_1589;
                ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1584 <= x1_V_read_reg_1584;
                ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1579 <= x2_V_read_reg_1579;
                ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1574 <= x3_V_read_reg_1574;
                ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1569 <= x4_V_read_reg_1569;
                ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1564 <= x5_V_read_reg_1564;
                ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1559 <= x6_V_read_reg_1559;
                ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1554 <= x7_V_read_reg_1554;
                or_cond1_3_reg_1603 <= or_cond1_3_fu_616_p2;
                or_cond2_4_reg_1607 <= or_cond2_4_fu_638_p2;
                or_cond3_5_reg_1611 <= or_cond3_5_fu_660_p2;
                or_cond4_6_reg_1615 <= or_cond4_6_fu_682_p2;
                or_cond5_7_reg_1619 <= or_cond5_7_fu_704_p2;
                or_cond6_8_reg_1623 <= or_cond6_8_fu_726_p2;
                or_cond7_9_reg_1627 <= or_cond7_9_fu_748_p2;
                or_cond_2_reg_1599 <= or_cond_2_fu_594_p2;
                sync_read_reg_1594 <= (0=>sync, others=>'-');
                x0_V_read_reg_1589 <= x0_V;
                x1_V_read_reg_1584 <= x1_V;
                x2_V_read_reg_1579 <= x2_V;
                x3_V_read_reg_1574 <= x3_V;
                x4_V_read_reg_1569 <= x4_V;
                x5_V_read_reg_1564 <= x5_V;
                x6_V_read_reg_1559 <= x6_V;
                x7_V_read_reg_1554 <= x7_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then
                ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1603 <= ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1603;
                ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1607 <= ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1607;
                ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1611 <= ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1611;
                ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1615 <= ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615;
                ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1619 <= ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619;
                ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1623 <= ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623;
                ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 <= ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627;
                ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1599 <= ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1599;
                ap_pipeline_reg_pp0_iter2_sync_read_reg_1594 <= ap_pipeline_reg_pp0_iter1_sync_read_reg_1594;
                ap_pipeline_reg_pp0_iter2_tmp_13_reg_1631 <= tmp_13_reg_1631;
                ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1589 <= ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1589;
                ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1584 <= ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1584;
                ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1579 <= ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1579;
                ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1574 <= ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1574;
                ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1569 <= ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1569;
                ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1564 <= ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1564;
                ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1559 <= ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1559;
                ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1554 <= ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1554;
                    v_assign_7_cast_reg_1710(2 downto 0) <= v_assign_7_cast_fu_869_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then
                count <= p_s_fu_1541_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0))) then
                g_11_reg_1676 <= g_11_fu_837_p2;
                tmp_35_reg_1683 <= tmp_35_fu_844_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0))) then
                g_12_reg_1690 <= g_12_fu_850_p2;
                tmp_44_reg_1697 <= tmp_44_fu_857_p2;
                tmp_45_reg_1704 <= tmp_45_fu_863_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (or_cond3_5_reg_1611 = ap_const_lv1_0))) then
                g_9_reg_1641 <= g_9_fu_790_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1627 = ap_const_lv1_0))) then
                g_reg_1715 <= g_fu_873_p2;
                tmp_54_reg_1723 <= tmp_54_fu_879_p2;
                tmp_55_reg_1730 <= tmp_55_fu_885_p2;
                tmp_57_reg_1736 <= tmp_57_fu_891_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (or_cond2_4_reg_1607 = ap_const_lv1_0))) then
                tmp_13_reg_1631 <= tmp_13_fu_780_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1611 = ap_const_lv1_0))) then
                tmp_19_reg_1647 <= tmp_19_fu_796_p2;
                tmp_20_reg_1653 <= tmp_20_fu_802_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0))) then
                tmp_27_reg_1658 <= tmp_27_fu_819_p2;
                tmp_28_reg_1665 <= tmp_28_fu_825_p2;
                tmp_30_reg_1671 <= tmp_30_fu_831_p2;
            end if;
        end if;
    end process;
    v_assign_7_cast_reg_1710(3) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);

    ap_condition_304_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_304 <= ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1));
    end process;


    ap_condition_340_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
                ap_condition_340 <= (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2));
    end process;


    ap_condition_41_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_41 <= ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))));
    end process;


    ap_done_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_precharge_reg_pp0_iter0_p_Val2_1_reg_334 <= "X";
    ap_phi_precharge_reg_pp0_iter1_iy_V_flag_1_reg_347 <= "X";
    ap_phi_precharge_reg_pp0_iter1_iy_V_flag_2_reg_378 <= "X";
    ap_phi_precharge_reg_pp0_iter1_iy_V_flag_3_reg_412 <= "X";
    ap_phi_precharge_reg_pp0_iter1_iy_V_new_1_reg_358 <= "X";
    ap_phi_precharge_reg_pp0_iter1_iy_V_new_2_reg_390 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_iy_V_new_3_reg_424 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_p_Val2_2_reg_369 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_p_Val2_4_reg_435 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_4_reg_444 <= "X";
    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_5_reg_475 <= "X";
    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_6_reg_521 <= "X";
    ap_phi_precharge_reg_pp0_iter2_iy_V_flag_7_reg_544 <= "X";
    ap_phi_precharge_reg_pp0_iter2_iy_V_new_4_reg_455 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_iy_V_new_5_reg_487 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_iy_V_new_6_reg_533 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_iy_V_new_7_reg_556 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_p_Val2_5_reg_465 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_p_Val2_6_reg_499 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_p_Val2_7_reg_510 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_p_Val2_8_reg_568 <= "XXXX";

    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    g_10_fu_812_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435));
    g_11_fu_837_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(p_Val2_5_phi_fu_468_p4));
    g_12_fu_850_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(p_Val2_6_phi_fu_502_p4));
    g_7_fu_759_p3 <= 
        ap_const_lv2_2 when (ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334(0) = '1') else 
        ap_const_lv2_1;
    g_8_fu_773_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(p_Val2_2_phi_fu_372_p4));
    g_9_fu_790_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(v_assign_3_cast_fu_786_p1));
    g_fu_873_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(v_assign_7_cast_fu_869_p1));
    iy_V <= iy_V_new_7_phi_fu_559_p4;

    iy_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, iy_V_flag_7_phi_fu_548_p4)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and not((ap_const_lv1_0 = iy_V_flag_7_phi_fu_548_p4)))) then 
            iy_V_ap_vld <= ap_const_logic_1;
        else 
            iy_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    iy_V_flag_1_phi_fu_350_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond1_3_reg_1603, ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334, ap_phi_precharge_reg_pp0_iter1_iy_V_flag_1_reg_347)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond1_3_reg_1603 = ap_const_lv1_0)) then 
                iy_V_flag_1_phi_fu_350_p4 <= ap_const_lv1_1;
            elsif (not((or_cond1_3_reg_1603 = ap_const_lv1_0))) then 
                iy_V_flag_1_phi_fu_350_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334;
            else 
                iy_V_flag_1_phi_fu_350_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_flag_1_reg_347;
            end if;
        else 
            iy_V_flag_1_phi_fu_350_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_flag_1_reg_347;
        end if; 
    end process;


    iy_V_flag_2_phi_fu_381_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond2_4_reg_1607, iy_V_flag_1_phi_fu_350_p4, ap_phi_precharge_reg_pp0_iter1_iy_V_flag_2_reg_378)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond2_4_reg_1607 = ap_const_lv1_0)) then 
                iy_V_flag_2_phi_fu_381_p4 <= ap_const_lv1_1;
            elsif (not((or_cond2_4_reg_1607 = ap_const_lv1_0))) then 
                iy_V_flag_2_phi_fu_381_p4 <= iy_V_flag_1_phi_fu_350_p4;
            else 
                iy_V_flag_2_phi_fu_381_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_flag_2_reg_378;
            end if;
        else 
            iy_V_flag_2_phi_fu_381_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_flag_2_reg_378;
        end if; 
    end process;


    iy_V_flag_4_phi_fu_447_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615, ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412, ap_phi_precharge_reg_pp0_iter2_iy_V_flag_4_reg_444)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0)) then 
                iy_V_flag_4_phi_fu_447_p4 <= ap_const_lv1_1;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0))) then 
                iy_V_flag_4_phi_fu_447_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_3_reg_412;
            else 
                iy_V_flag_4_phi_fu_447_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_4_reg_444;
            end if;
        else 
            iy_V_flag_4_phi_fu_447_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_4_reg_444;
        end if; 
    end process;


    iy_V_flag_5_phi_fu_478_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619, iy_V_flag_4_phi_fu_447_p4, ap_phi_precharge_reg_pp0_iter2_iy_V_flag_5_reg_475)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0)) then 
                iy_V_flag_5_phi_fu_478_p4 <= ap_const_lv1_1;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0))) then 
                iy_V_flag_5_phi_fu_478_p4 <= iy_V_flag_4_phi_fu_447_p4;
            else 
                iy_V_flag_5_phi_fu_478_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_5_reg_475;
            end if;
        else 
            iy_V_flag_5_phi_fu_478_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_flag_5_reg_475;
        end if; 
    end process;


    iy_V_flag_7_phi_fu_548_p4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627, ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521, ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter3) and not((ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 = ap_const_lv1_0)))) then 
            iy_V_flag_7_phi_fu_548_p4 <= ap_phi_precharge_reg_pp0_iter3_iy_V_flag_6_reg_521;
        else 
            iy_V_flag_7_phi_fu_548_p4 <= ap_phi_precharge_reg_pp0_iter3_iy_V_flag_7_reg_544;
        end if; 
    end process;

    iy_V_new_1_cast_fu_768_p1 <= std_logic_vector(resize(unsigned(iy_V_new_1_phi_fu_361_p4),2));

    iy_V_new_1_phi_fu_361_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond1_3_reg_1603, ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334, ap_phi_precharge_reg_pp0_iter1_iy_V_new_1_reg_358)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond1_3_reg_1603 = ap_const_lv1_0)) then 
                iy_V_new_1_phi_fu_361_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334;
            elsif (not((or_cond1_3_reg_1603 = ap_const_lv1_0))) then 
                iy_V_new_1_phi_fu_361_p4 <= ap_const_lv1_0;
            else 
                iy_V_new_1_phi_fu_361_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_new_1_reg_358;
            end if;
        else 
            iy_V_new_1_phi_fu_361_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_new_1_reg_358;
        end if; 
    end process;


    iy_V_new_2_phi_fu_393_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond2_4_reg_1607, p_Val2_2_phi_fu_372_p4, iy_V_new_1_cast_fu_768_p1, ap_phi_precharge_reg_pp0_iter1_iy_V_new_2_reg_390)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond2_4_reg_1607 = ap_const_lv1_0)) then 
                iy_V_new_2_phi_fu_393_p4 <= p_Val2_2_phi_fu_372_p4;
            elsif (not((or_cond2_4_reg_1607 = ap_const_lv1_0))) then 
                iy_V_new_2_phi_fu_393_p4 <= iy_V_new_1_cast_fu_768_p1;
            else 
                iy_V_new_2_phi_fu_393_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_new_2_reg_390;
            end if;
        else 
            iy_V_new_2_phi_fu_393_p4 <= ap_phi_precharge_reg_pp0_iter1_iy_V_new_2_reg_390;
        end if; 
    end process;

    iy_V_new_3_cast_fu_807_p1 <= std_logic_vector(resize(unsigned(ap_phi_precharge_reg_pp0_iter2_iy_V_new_3_reg_424),3));

    iy_V_new_4_phi_fu_458_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615, ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435, iy_V_new_3_cast_fu_807_p1, ap_phi_precharge_reg_pp0_iter2_iy_V_new_4_reg_455)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0)) then 
                iy_V_new_4_phi_fu_458_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0))) then 
                iy_V_new_4_phi_fu_458_p4 <= iy_V_new_3_cast_fu_807_p1;
            else 
                iy_V_new_4_phi_fu_458_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_4_reg_455;
            end if;
        else 
            iy_V_new_4_phi_fu_458_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_4_reg_455;
        end if; 
    end process;


    iy_V_new_5_phi_fu_490_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619, iy_V_new_4_phi_fu_458_p4, p_Val2_5_phi_fu_468_p4, ap_phi_precharge_reg_pp0_iter2_iy_V_new_5_reg_487)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0)) then 
                iy_V_new_5_phi_fu_490_p4 <= p_Val2_5_phi_fu_468_p4;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0))) then 
                iy_V_new_5_phi_fu_490_p4 <= iy_V_new_4_phi_fu_458_p4;
            else 
                iy_V_new_5_phi_fu_490_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_5_reg_487;
            end if;
        else 
            iy_V_new_5_phi_fu_490_p4 <= ap_phi_precharge_reg_pp0_iter2_iy_V_new_5_reg_487;
        end if; 
    end process;


    iy_V_new_7_phi_fu_559_p4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627, ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533, ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter3) and not((ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 = ap_const_lv1_0)))) then 
            iy_V_new_7_phi_fu_559_p4 <= ap_phi_precharge_reg_pp0_iter3_iy_V_new_6_reg_533;
        else 
            iy_V_new_7_phi_fu_559_p4 <= ap_phi_precharge_reg_pp0_iter3_iy_V_new_7_reg_556;
        end if; 
    end process;

    newSel100_cast_fu_1188_p1 <= std_logic_vector(resize(unsigned(newSel4_fu_1180_p3),14));
    newSel104_cast_cast_fu_1298_p3 <= 
        ap_const_lv3_3 when (sel_tmp15_fu_1242_p2(0) = '1') else 
        ap_const_lv3_2;
    newSel106_cast_cast_fu_1312_p3 <= 
        ap_const_lv3_1 when (tmp_44_reg_1697(0) = '1') else 
        ap_const_lv3_6;
    newSel10_fu_1494_p3 <= 
        newSel8_fu_1453_p3 when (or_cond7_fu_1461_p2(0) = '1') else 
        newSel9_fu_1467_p3;
    newSel110_cast_fu_1341_p1 <= std_logic_vector(resize(unsigned(newSel7_fu_1333_p3),14));
    newSel116_cast_cast_fu_1481_p3 <= 
        ap_const_lv3_2 when (sel_tmp21_fu_1380_p2(0) = '1') else 
        ap_const_lv3_1;
    newSel11_fu_1508_p3 <= 
        newSel116_cast_cast_fu_1481_p3 when (or_cond9_fu_1489_p2(0) = '1') else 
        ap_const_lv3_7;
    newSel122_cast_fu_1524_p1 <= std_logic_vector(resize(unsigned(newSel12_fu_1516_p3),14));
    newSel12_fu_1516_p3 <= 
        newSel10_fu_1494_p3 when (or_cond10_fu_1502_p2(0) = '1') else 
        newSel11_fu_1508_p3;
    newSel1_fu_1051_p3 <= 
        newSel_cast_cast_fu_1030_p3 when (or_cond_fu_1038_p2(0) = '1') else 
        newSel_fu_1044_p3;
    newSel2_fu_1139_p3 <= 
        ap_const_lv3_4 when (sel_tmp11_fu_1133_p2(0) = '1') else 
        ap_const_lv3_3;
    newSel3_fu_1166_p3 <= 
        newSel2_fu_1139_p3 when (or_cond1_fu_1147_p2(0) = '1') else 
        newSel96_cast_cast_fu_1153_p3;
    newSel4_fu_1180_p3 <= 
        newSel3_fu_1166_p3 when (or_cond3_fu_1174_p2(0) = '1') else 
        ap_const_lv3_5;
    newSel5_fu_1284_p3 <= 
        ap_const_lv3_5 when (sel_tmp19_fu_1278_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel6_fu_1319_p3 <= 
        newSel5_fu_1284_p3 when (or_cond4_fu_1292_p2(0) = '1') else 
        newSel104_cast_cast_fu_1298_p3;
    newSel7_fu_1333_p3 <= 
        newSel6_fu_1319_p3 when (or_cond6_fu_1327_p2(0) = '1') else 
        newSel106_cast_cast_fu_1312_p3;
    newSel8_fu_1453_p3 <= 
        ap_const_lv3_6 when (sel_tmp29_fu_1447_p2(0) = '1') else 
        ap_const_lv3_5;
    newSel92_cast_fu_1059_p1 <= std_logic_vector(resize(unsigned(newSel1_fu_1051_p3),14));
    newSel96_cast_cast_fu_1153_p3 <= 
        ap_const_lv3_2 when (sel_tmp7_fu_1098_p2(0) = '1') else 
        ap_const_lv3_1;
    newSel9_fu_1467_p3 <= 
        ap_const_lv3_4 when (sel_tmp25_fu_1411_p2(0) = '1') else 
        ap_const_lv3_3;
    newSel_cast_cast_fu_1030_p3 <= 
        ap_const_lv3_3 when (sel_tmp3_fu_1025_p2(0) = '1') else 
        ap_const_lv3_2;
    newSel_fu_1044_p3 <= 
        ap_const_lv3_1 when (tmp_27_reg_1658(0) = '1') else 
        ap_const_lv3_4;
    or_cond10_fu_1502_p2 <= (or_cond7_fu_1461_p2 or or_cond8_fu_1475_p2);
    or_cond1_3_fu_616_p2 <= (tmp_6_fu_604_p2 and tmp_7_fu_610_p2);
    or_cond1_fu_1147_p2 <= (sel_tmp11_fu_1133_p2 or sel_tmp9_fu_1115_p2);
    or_cond2_4_fu_638_p2 <= (tmp_10_fu_626_p2 and tmp_11_fu_632_p2);
    or_cond2_fu_1161_p2 <= (sel_tmp7_fu_1098_p2 or tmp_35_reg_1683);
    or_cond3_5_fu_660_p2 <= (tmp_16_fu_648_p2 and tmp_17_fu_654_p2);
    or_cond3_fu_1174_p2 <= (or_cond1_fu_1147_p2 or or_cond2_fu_1161_p2);
    or_cond4_6_fu_682_p2 <= (tmp_24_fu_670_p2 and tmp_25_fu_676_p2);
    or_cond4_fu_1292_p2 <= (sel_tmp19_fu_1278_p2 or sel_tmp17_fu_1260_p2);
    or_cond5_7_fu_704_p2 <= (tmp_32_fu_692_p2 and tmp_33_fu_698_p2);
    or_cond5_fu_1306_p2 <= (sel_tmp15_fu_1242_p2 or sel_tmp13_fu_1227_p2);
    or_cond6_8_fu_726_p2 <= (tmp_41_fu_714_p2 and tmp_42_fu_720_p2);
    or_cond6_fu_1327_p2 <= (or_cond4_fu_1292_p2 or or_cond5_fu_1306_p2);
    or_cond7_9_fu_748_p2 <= (tmp_51_fu_736_p2 and tmp_52_fu_742_p2);
    or_cond7_fu_1461_p2 <= (sel_tmp29_fu_1447_p2 or sel_tmp27_fu_1429_p2);
    or_cond8_fu_1475_p2 <= (sel_tmp25_fu_1411_p2 or sel_tmp23_fu_1395_p2);
    or_cond9_fu_1489_p2 <= (sel_tmp21_fu_1380_p2 or tmp_54_reg_1723);
    or_cond_2_fu_594_p2 <= (tmp_1_fu_582_p2 and tmp_2_fu_588_p2);
    or_cond_fu_1038_p2 <= (sel_tmp3_fu_1025_p2 or sel_tmp6_fu_1010_p2);

    p_Val2_2_phi_fu_372_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond1_3_reg_1603, v_assign_1_cast_fu_754_p1, ap_phi_precharge_reg_pp0_iter1_p_Val2_2_reg_369, g_7_fu_759_p3)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond1_3_reg_1603 = ap_const_lv1_0)) then 
                p_Val2_2_phi_fu_372_p4 <= g_7_fu_759_p3;
            elsif (not((or_cond1_3_reg_1603 = ap_const_lv1_0))) then 
                p_Val2_2_phi_fu_372_p4 <= v_assign_1_cast_fu_754_p1;
            else 
                p_Val2_2_phi_fu_372_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_2_reg_369;
            end if;
        else 
            p_Val2_2_phi_fu_372_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_2_reg_369;
        end if; 
    end process;


    p_Val2_3_phi_fu_404_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond2_4_reg_1607, p_Val2_2_phi_fu_372_p4, ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401, g_8_fu_773_p2)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if ((or_cond2_4_reg_1607 = ap_const_lv1_0)) then 
                p_Val2_3_phi_fu_404_p4 <= g_8_fu_773_p2;
            elsif (not((or_cond2_4_reg_1607 = ap_const_lv1_0))) then 
                p_Val2_3_phi_fu_404_p4 <= p_Val2_2_phi_fu_372_p4;
            else 
                p_Val2_3_phi_fu_404_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401;
            end if;
        else 
            p_Val2_3_phi_fu_404_p4 <= ap_phi_precharge_reg_pp0_iter1_p_Val2_3_reg_401;
        end if; 
    end process;


    p_Val2_5_phi_fu_468_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615, ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435, ap_phi_precharge_reg_pp0_iter2_p_Val2_5_reg_465, g_10_fu_812_p2)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0)) then 
                p_Val2_5_phi_fu_468_p4 <= g_10_fu_812_p2;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1615 = ap_const_lv1_0))) then 
                p_Val2_5_phi_fu_468_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435;
            else 
                p_Val2_5_phi_fu_468_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_5_reg_465;
            end if;
        else 
            p_Val2_5_phi_fu_468_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_5_reg_465;
        end if; 
    end process;


    p_Val2_6_phi_fu_502_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619, g_11_fu_837_p2, p_Val2_5_phi_fu_468_p4, ap_phi_precharge_reg_pp0_iter2_p_Val2_6_reg_499)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0)) then 
                p_Val2_6_phi_fu_502_p4 <= g_11_fu_837_p2;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1619 = ap_const_lv1_0))) then 
                p_Val2_6_phi_fu_502_p4 <= p_Val2_5_phi_fu_468_p4;
            else 
                p_Val2_6_phi_fu_502_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_6_reg_499;
            end if;
        else 
            p_Val2_6_phi_fu_502_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_6_reg_499;
        end if; 
    end process;


    p_Val2_7_phi_fu_513_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623, g_12_fu_850_p2, p_Val2_6_phi_fu_502_p4, ap_phi_precharge_reg_pp0_iter2_p_Val2_7_reg_510)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if ((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0)) then 
                p_Val2_7_phi_fu_513_p4 <= g_12_fu_850_p2;
            elsif (not((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1623 = ap_const_lv1_0))) then 
                p_Val2_7_phi_fu_513_p4 <= p_Val2_6_phi_fu_502_p4;
            else 
                p_Val2_7_phi_fu_513_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_7_reg_510;
            end if;
        else 
            p_Val2_7_phi_fu_513_p4 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_7_reg_510;
        end if; 
    end process;


    p_Val2_8_phi_fu_571_p4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627, v_assign_7_cast_reg_1710, ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter3) and not((ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 = ap_const_lv1_0)))) then 
            p_Val2_8_phi_fu_571_p4 <= v_assign_7_cast_reg_1710;
        else 
            p_Val2_8_phi_fu_571_p4 <= ap_phi_precharge_reg_pp0_iter3_p_Val2_8_reg_568;
        end if; 
    end process;

    p_s_fu_1541_p3 <= 
        ap_const_lv32_0 when (ap_pipeline_reg_pp0_iter2_sync_read_reg_1594(0) = '1') else 
        tmp_61_fu_1535_p2;
    sel_tmp10_demorgan_fu_1015_p2 <= (tmp_27_reg_1658 or tmp_28_reg_1665);
    sel_tmp10_fu_1127_p2 <= (sel_tmp26_demorgan_fu_1121_p2 xor ap_const_lv1_1);
    sel_tmp11_fu_1133_p2 <= (tmp_39_fu_1088_p2 and sel_tmp10_fu_1127_p2);
    sel_tmp12_fu_1222_p2 <= (tmp_44_reg_1697 xor ap_const_lv1_1);
    sel_tmp13_fu_1227_p2 <= (tmp_45_reg_1704 and sel_tmp12_fu_1222_p2);
    sel_tmp14_fu_1236_p2 <= (sel_tmp35_demorgan_fu_1232_p2 xor ap_const_lv1_1);
    sel_tmp15_fu_1242_p2 <= (tmp_47_fu_1207_p2 and sel_tmp14_fu_1236_p2);
    sel_tmp16_fu_1254_p2 <= (sel_tmp42_demorgan_fu_1248_p2 xor ap_const_lv1_1);
    sel_tmp17_fu_1260_p2 <= (tmp_48_fu_1212_p2 and sel_tmp16_fu_1254_p2);
    sel_tmp18_fu_1272_p2 <= (sel_tmp51_demorgan_fu_1266_p2 xor ap_const_lv1_1);
    sel_tmp19_demorgan_fu_1104_p2 <= (tmp_35_reg_1683 or tmp_36_fu_1078_p2);
    sel_tmp19_fu_1278_p2 <= (tmp_49_fu_1217_p2 and sel_tmp18_fu_1272_p2);
    sel_tmp1_fu_955_p2 <= (tmp_19_reg_1647 xor ap_const_lv1_1);
    sel_tmp20_fu_1375_p2 <= (tmp_54_reg_1723 xor ap_const_lv1_1);
    sel_tmp21_fu_1380_p2 <= (tmp_55_reg_1730 and sel_tmp20_fu_1375_p2);
    sel_tmp22_fu_1389_p2 <= (sel_tmp60_demorgan_fu_1385_p2 xor ap_const_lv1_1);
    sel_tmp23_fu_1395_p2 <= (tmp_57_reg_1736 and sel_tmp22_fu_1389_p2);
    sel_tmp24_fu_1405_p2 <= (sel_tmp67_demorgan_fu_1400_p2 xor ap_const_lv1_1);
    sel_tmp25_fu_1411_p2 <= (tmp_58_fu_1360_p2 and sel_tmp24_fu_1405_p2);
    sel_tmp26_demorgan_fu_1121_p2 <= (sel_tmp19_demorgan_fu_1104_p2 or tmp_38_fu_1083_p2);
    sel_tmp26_fu_1423_p2 <= (sel_tmp76_demorgan_fu_1417_p2 xor ap_const_lv1_1);
    sel_tmp27_fu_1429_p2 <= (tmp_59_fu_1365_p2 and sel_tmp26_fu_1423_p2);
    sel_tmp28_fu_1441_p2 <= (sel_tmp87_demorgan_fu_1435_p2 xor ap_const_lv1_1);
    sel_tmp29_fu_1447_p2 <= (tmp_60_fu_1370_p2 and sel_tmp28_fu_1441_p2);
    sel_tmp2_fu_960_p2 <= (tmp_20_reg_1653 and sel_tmp1_fu_955_p2);
    sel_tmp35_demorgan_fu_1232_p2 <= (tmp_44_reg_1697 or tmp_45_reg_1704);
    sel_tmp3_fu_1025_p2 <= (tmp_30_reg_1671 and sel_tmp_fu_1019_p2);
    sel_tmp42_demorgan_fu_1248_p2 <= (sel_tmp35_demorgan_fu_1232_p2 or tmp_47_fu_1207_p2);
    sel_tmp4_fu_1093_p2 <= (tmp_35_reg_1683 xor ap_const_lv1_1);
    sel_tmp51_demorgan_fu_1266_p2 <= (sel_tmp42_demorgan_fu_1248_p2 or tmp_48_fu_1212_p2);
    sel_tmp5_fu_1005_p2 <= (tmp_27_reg_1658 xor ap_const_lv1_1);
    sel_tmp60_demorgan_fu_1385_p2 <= (tmp_54_reg_1723 or tmp_55_reg_1730);
    sel_tmp67_demorgan_fu_1400_p2 <= (sel_tmp60_demorgan_fu_1385_p2 or tmp_57_reg_1736);
    sel_tmp6_fu_1010_p2 <= (tmp_28_reg_1665 and sel_tmp5_fu_1005_p2);
    sel_tmp76_demorgan_fu_1417_p2 <= (sel_tmp67_demorgan_fu_1400_p2 or tmp_58_fu_1360_p2);
    sel_tmp7_fu_1098_p2 <= (tmp_36_fu_1078_p2 and sel_tmp4_fu_1093_p2);
    sel_tmp87_demorgan_fu_1435_p2 <= (sel_tmp76_demorgan_fu_1417_p2 or tmp_59_fu_1365_p2);
    sel_tmp8_fu_1109_p2 <= (sel_tmp19_demorgan_fu_1104_p2 xor ap_const_lv1_1);
    sel_tmp9_fu_1115_p2 <= (tmp_38_fu_1083_p2 and sel_tmp8_fu_1109_p2);
    sel_tmp_fu_1019_p2 <= (sel_tmp10_demorgan_fu_1015_p2 xor ap_const_lv1_1);
    sel_tmp_v_fu_965_p3 <= 
        ap_const_lv2_2 when (sel_tmp2_fu_960_p2(0) = '1') else 
        ap_const_lv2_1;
    storemerge1_v_cast_c_fu_933_p3 <= 
        ap_const_lv14_1 when (ap_pipeline_reg_pp0_iter2_tmp_13_reg_1631(0) = '1') else 
        ap_const_lv14_2;
    storemerge4_v_cast_fu_986_p1 <= std_logic_vector(resize(unsigned(storemerge4_v_fu_978_p3),14));
    storemerge4_v_fu_978_p3 <= 
        sel_tmp_v_fu_965_p3 when (tmp_22_fu_973_p2(0) = '1') else 
        ap_const_lv2_3;
    t0_V <= count(14 - 1 downto 0);

    t0_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1599)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1599 = ap_const_lv1_0))) then 
            t0_V_ap_vld <= ap_const_logic_1;
        else 
            t0_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t1_V <= std_logic_vector(unsigned(ap_const_lv14_1) + unsigned(tmp_15_fu_914_p1));

    t1_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1603)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1603 = ap_const_lv1_0))) then 
            t1_V_ap_vld <= ap_const_logic_1;
        else 
            t1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t2_V <= std_logic_vector(unsigned(storemerge1_v_cast_c_fu_933_p3) + unsigned(tmp_21_fu_929_p1));

    t2_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1607)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1607 = ap_const_lv1_0))) then 
            t2_V_ap_vld <= ap_const_logic_1;
        else 
            t2_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t3_V <= std_logic_vector(unsigned(storemerge4_v_cast_fu_986_p1) + unsigned(tmp_29_fu_951_p1));

    t3_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1611)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1611 = ap_const_lv1_0))) then 
            t3_V_ap_vld <= ap_const_logic_1;
        else 
            t3_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t4_V <= std_logic_vector(unsigned(newSel92_cast_fu_1059_p1) + unsigned(tmp_37_fu_1001_p1));

    t4_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1615)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1615 = ap_const_lv1_0))) then 
            t4_V_ap_vld <= ap_const_logic_1;
        else 
            t4_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t5_V <= std_logic_vector(unsigned(newSel100_cast_fu_1188_p1) + unsigned(tmp_46_fu_1074_p1));

    t5_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1619)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1619 = ap_const_lv1_0))) then 
            t5_V_ap_vld <= ap_const_logic_1;
        else 
            t5_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t6_V <= std_logic_vector(unsigned(newSel110_cast_fu_1341_p1) + unsigned(tmp_56_fu_1203_p1));

    t6_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1623)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1623 = ap_const_lv1_0))) then 
            t6_V_ap_vld <= ap_const_logic_1;
        else 
            t6_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t7_V <= std_logic_vector(unsigned(newSel122_cast_fu_1524_p1) + unsigned(tmp_63_fu_1356_p1));

    t7_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1627 = ap_const_lv1_0))) then 
            t7_V_ap_vld <= ap_const_logic_1;
        else 
            t7_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_626_p2 <= "1" when (signed(tmp_s_fu_622_p1) > signed(config_a)) else "0";
    tmp_11_fu_632_p2 <= "1" when (signed(tmp_s_fu_622_p1) < signed(config_b)) else "0";
    tmp_13_fu_780_p2 <= "1" when (p_Val2_2_phi_fu_372_p4 = ap_const_lv2_0) else "0";
    tmp_14_fu_644_p1 <= std_logic_vector(resize(unsigned(x3_V),32));
    tmp_15_fu_914_p1 <= count(14 - 1 downto 0);
    tmp_16_fu_648_p2 <= "1" when (signed(tmp_14_fu_644_p1) > signed(config_a)) else "0";
    tmp_17_fu_654_p2 <= "1" when (signed(tmp_14_fu_644_p1) < signed(config_b)) else "0";
    tmp_19_fu_796_p2 <= "1" when (p_Val2_3_reg_401 = ap_const_lv2_0) else "0";
    tmp_1_fu_582_p2 <= "1" when (signed(tmp_fu_578_p1) > signed(config_a)) else "0";
    tmp_20_fu_802_p2 <= "1" when (g_9_reg_1641 = ap_const_lv3_2) else "0";
    tmp_21_fu_929_p1 <= count(14 - 1 downto 0);
    tmp_22_fu_973_p2 <= (sel_tmp2_fu_960_p2 or tmp_19_reg_1647);
    tmp_23_fu_666_p1 <= std_logic_vector(resize(unsigned(x4_V),32));
    tmp_24_fu_670_p2 <= "1" when (signed(tmp_23_fu_666_p1) > signed(config_a)) else "0";
    tmp_25_fu_676_p2 <= "1" when (signed(tmp_23_fu_666_p1) < signed(config_b)) else "0";
    tmp_27_fu_819_p2 <= "1" when (ap_phi_precharge_reg_pp0_iter2_p_Val2_4_reg_435 = ap_const_lv3_0) else "0";
    tmp_28_fu_825_p2 <= "1" when (g_10_fu_812_p2 = ap_const_lv3_2) else "0";
    tmp_29_fu_951_p1 <= count(14 - 1 downto 0);
    tmp_2_fu_588_p2 <= "1" when (signed(tmp_fu_578_p1) < signed(config_b)) else "0";
    tmp_30_fu_831_p2 <= "1" when (g_10_fu_812_p2 = ap_const_lv3_3) else "0";
    tmp_31_fu_688_p1 <= std_logic_vector(resize(unsigned(x5_V),32));
    tmp_32_fu_692_p2 <= "1" when (signed(tmp_31_fu_688_p1) > signed(config_a)) else "0";
    tmp_33_fu_698_p2 <= "1" when (signed(tmp_31_fu_688_p1) < signed(config_b)) else "0";
    tmp_35_fu_844_p2 <= "1" when (p_Val2_5_phi_fu_468_p4 = ap_const_lv3_0) else "0";
    tmp_36_fu_1078_p2 <= "1" when (g_11_reg_1676 = ap_const_lv3_2) else "0";
    tmp_37_fu_1001_p1 <= count(14 - 1 downto 0);
    tmp_38_fu_1083_p2 <= "1" when (g_11_reg_1676 = ap_const_lv3_3) else "0";
    tmp_39_fu_1088_p2 <= "1" when (g_11_reg_1676 = ap_const_lv3_4) else "0";
    tmp_40_fu_710_p1 <= std_logic_vector(resize(unsigned(x6_V),32));
    tmp_41_fu_714_p2 <= "1" when (signed(tmp_40_fu_710_p1) > signed(config_a)) else "0";
    tmp_42_fu_720_p2 <= "1" when (signed(tmp_40_fu_710_p1) < signed(config_b)) else "0";
    tmp_44_fu_857_p2 <= "1" when (p_Val2_6_phi_fu_502_p4 = ap_const_lv3_0) else "0";
    tmp_45_fu_863_p2 <= "1" when (g_12_fu_850_p2 = ap_const_lv3_2) else "0";
    tmp_46_fu_1074_p1 <= count(14 - 1 downto 0);
    tmp_47_fu_1207_p2 <= "1" when (g_12_reg_1690 = ap_const_lv3_3) else "0";
    tmp_48_fu_1212_p2 <= "1" when (g_12_reg_1690 = ap_const_lv3_4) else "0";
    tmp_49_fu_1217_p2 <= "1" when (g_12_reg_1690 = ap_const_lv3_5) else "0";
    tmp_50_fu_732_p1 <= std_logic_vector(resize(unsigned(x7_V),32));
    tmp_51_fu_736_p2 <= "1" when (signed(tmp_50_fu_732_p1) > signed(config_a)) else "0";
    tmp_52_fu_742_p2 <= "1" when (signed(tmp_50_fu_732_p1) < signed(config_b)) else "0";
    tmp_54_fu_879_p2 <= "1" when (p_Val2_7_phi_fu_513_p4 = ap_const_lv3_0) else "0";
    tmp_55_fu_885_p2 <= "1" when (g_fu_873_p2 = ap_const_lv4_2) else "0";
    tmp_56_fu_1203_p1 <= count(14 - 1 downto 0);
    tmp_57_fu_891_p2 <= "1" when (g_fu_873_p2 = ap_const_lv4_3) else "0";
    tmp_58_fu_1360_p2 <= "1" when (g_reg_1715 = ap_const_lv4_4) else "0";
    tmp_59_fu_1365_p2 <= "1" when (g_reg_1715 = ap_const_lv4_5) else "0";
    tmp_5_fu_600_p1 <= std_logic_vector(resize(unsigned(x1_V),32));
    tmp_60_fu_1370_p2 <= "1" when (g_reg_1715 = ap_const_lv4_6) else "0";
    tmp_61_fu_1535_p2 <= std_logic_vector(unsigned(count) + unsigned(ap_const_lv32_8));
    tmp_63_fu_1356_p1 <= count(14 - 1 downto 0);
    tmp_6_fu_604_p2 <= "1" when (signed(tmp_5_fu_600_p1) > signed(config_a)) else "0";
    tmp_7_fu_610_p2 <= "1" when (signed(tmp_5_fu_600_p1) < signed(config_b)) else "0";
    tmp_fu_578_p1 <= std_logic_vector(resize(unsigned(x0_V),32));
    tmp_s_fu_622_p1 <= std_logic_vector(resize(unsigned(x2_V),32));
    v_assign_1_cast_fu_754_p1 <= std_logic_vector(resize(unsigned(ap_phi_precharge_reg_pp0_iter1_p_Val2_1_reg_334),2));
    v_assign_3_cast_fu_786_p1 <= std_logic_vector(resize(unsigned(p_Val2_3_phi_fu_404_p4),3));
    v_assign_7_cast_fu_869_p1 <= std_logic_vector(resize(unsigned(p_Val2_7_phi_fu_513_p4),4));
    y0_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1589),16));
    y1_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1584),16));
    y2_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1579),16));
    y3_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1574),16));
    y4_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1569),16));
    y5_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1564),16));
    y6_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1559),16));
    y7_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1554),16));
    yv_V <= p_Val2_8_phi_fu_571_p4;
end behav;
